USE phone_db;

INSERT INTO posts (title, content, image_url, topic_id, author_id, created_at) VALUES 
('Lộ diện iPhone 16 Pro Max: Viền mỏng kỷ lục, chip A18 Pro siêu mạnh', 'Theo các rò rỉ mới nhất, iPhone 16 Pro Max sẽ có thiết kế viền màn hình siêu mỏng, chỉ 1.15mm, phá vỡ mọi kỷ lục trước đó. Máy sẽ được trang bị con chip A18 Pro với khả năng xử lý AI cục bộ (On-device AI) vô cùng mạnh mẽ. Camera cũng được nâng cấp với cảm biến chính lớn hơn. Sự ra mắt của dòng sản phẩm mới này hứa hẹn sẽ mang lại trải nghiệm đỉnh cao cho iFan.', 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?q=80&w=2070&auto=format&fit=crop', 1, 17, NOW()),

('Bão Sale Nửa Tháng: Cơ hội ngàn vàng sắm điện thoại mới', 'Chương trình ưu đãi lớn nhất giữa tháng đã chính thức bắt đầu! Hàng ngàn mẫu điện thoại từ iPhone, Samsung đến Xiaomi đều được giảm giá sâu. Đặc biệt, chúng tôi tặng bạn mã giảm giá độc quyền. Hãy sử dụng ngay mã sau để được giảm trực tiếp 200K vào đơn hàng: [VOUCHER: SALEGIUATHANG]. Số lượng mã có hạn, hãy nhanh tay lưu lại và sử dụng ngay hôm nay!', 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=2070&auto=format&fit=crop', 3, 17, NOW()),

('5 Mẹo tiết kiệm pin cực hay trên iOS 18 bạn nên biết', 'iOS 18 mang đến nhiều tính năng mới nhưng cũng có thể làm hao pin nhanh hơn nếu bạn không biết cách tối ưu. Dưới đây là 5 mẹo nhỏ:\n1. Tắt làm mới ứng dụng trong nền.\n2. Bật chế độ tối (Dark Mode).\n3. Tắt dịch vụ định vị cho các ứng dụng không cần thiết.\n4. Giảm độ sáng màn hình tự động.\n5. Xóa các widget không sử dụng trên màn hình chính.\nHãy thử ngay để tăng thời lượng sử dụng nhé!', 'https://images.unsplash.com/photo-1556656793-08538906a9f8?q=80&w=2070&auto=format&fit=crop', 1, 17, NOW()),

('Review AirPods Pro 3: Chống ồn đỉnh cao, âm thanh vòm không gian xuất sắc', 'Thế hệ tai nghe không dây mới nhất của Apple đã chính thức ra mắt. AirPods Pro 3 mang đến khả năng chống ồn chủ động (ANC) tốt gấp đôi thế hệ trước. Đặc biệt, tính năng âm thanh vòm (Spatial Audio) được cải tiến, tự động theo dõi chuyển động đầu cực kỳ mượt mà. Thời lượng pin cũng được nâng cấp lên đến 6 giờ nghe nhạc liên tục. Chắc chắn đây là phụ kiện không thể thiếu.', 'https://images.unsplash.com/photo-1606220838315-056192d5e927?q=80&w=2070&auto=format&fit=crop', 1, 17, NOW()),

('Mùa Tựu Trường - Nhận Khuyến Mãi Khủng', 'Chào mừng năm học mới, Mobitech mang đến chương trình "Tựu Trường Sành Điệu - Sắm Táo Hàng Hiệu". Dành riêng cho học sinh, sinh viên, chúng tôi tặng bạn một mã giảm giá siêu đặc biệt lên đến 500.000đ khi mua laptop hoặc iPad. Lưu ngay mã này vào ví của bạn: [VOUCHER: BACK2SCHOOL]. Chúc các bạn một năm học mới nhiều niềm vui và thành công!', 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=2070&auto=format&fit=crop', 3, 17, NOW()),

('Top 5 Điện thoại chơi game tốt nhất đầu năm 2026', 'Nếu bạn là một game thủ mobile thực thụ, đừng bỏ qua danh sách này:\n1. ROG Phone 8 Pro: Vua tản nhiệt.\n2. iPhone 15 Pro Max: Hiệu năng ổn định nhờ chip A17 Pro.\n3. RedMagic 9 Pro: Thiết kế gaming hầm hố, pin trâu.\n4. Samsung Galaxy S24 Ultra: Màn hình lớn, tần số quét cao.\n5. Xiaomi 14 Pro: Sạc siêu nhanh.\nHãy chọn cho mình chiếc máy phù hợp để leo rank nhé!', 'https://images.unsplash.com/photo-1580234811497-9df7f5022e03?q=80&w=2067&auto=format&fit=crop', 1, 17, NOW()),

('Hướng dẫn chụp ảnh chân dung (Portrait) siêu đẹp bằng iPhone', 'Camera của iPhone cực kỳ mạnh mẽ nếu bạn biết cách làm chủ nó. Khi chụp ảnh chân dung, hãy lưu ý:\n- Chọn ánh sáng tự nhiên, tốt nhất là vào khung giờ vàng (Golden Hour).\n- Tận dụng chế độ Portrait Lighting (Ánh sáng studio) để làm nổi bật khuôn mặt.\n- Xóa phông (Depth Control) vừa phải (khoảng f/2.8 - f/4.0) để trông tự nhiên nhất.\nChúc bạn có những bức ảnh triệu like!', 'https://images.unsplash.com/photo-1516724562728-afc824a36e84?q=80&w=2071&auto=format&fit=crop', 1, 17, NOW()),

('Black Friday Đã Đến - Săn Sale Xuyên Màn Đêm', 'Ngày hội mua sắm lớn nhất năm đã chính thức đổ bộ Mobitech! Các sản phẩm công nghệ giảm giá lên đến 50%. Để tri ân khách hàng thân thiết, chúng tôi tung ra mã giảm giá siêu cấp vũ trụ. Click để lưu mã: [VOUCHER: BLACKFRIDAY500K]. Hãy nhanh tay lên vì mã chỉ có giá trị trong 24 giờ tới và số lượng rất có hạn!', 'https://images.unsplash.com/photo-1607082349566-187342175e2f?q=80&w=2070&auto=format&fit=crop', 3, 17, NOW()),

('So sánh iPhone 15 Pro và iPhone 14 Pro: Có đáng để nâng cấp?', 'Thiết kế Titanium nhẹ hơn đáng kể so với viền thép không gỉ. Cổng USB-C mở ra một hệ sinh thái phụ kiện mới. Nút Action Button mang lại khả năng tùy biến cao. Nếu bạn đang dùng iPhone 14 Pro, nâng cấp có thể không quá rõ rệt, nhưng nếu từ iPhone 13 Pro trở xuống, đây là một bước nhảy vọt hoàn toàn xứng đáng.', 'https://images.unsplash.com/photo-1695048133142-1a20a5bf616f?q=80&w=2070&auto=format&fit=crop', 1, 17, NOW()),

('Flash Sale Chớp Nhoáng: Ưu đãi bất ngờ chỉ trong 2 giờ', 'Chỉ duy nhất trong khung giờ từ 20:00 đến 22:00 tối nay, chúng tôi mang đến cho bạn một món quà bất ngờ. Đừng bỏ lỡ cơ hội sở hữu phụ kiện công nghệ với giá cực hời. Sử dụng ngay mã giảm giá đặc biệt này: [VOUCHER: FLASHSALE99K]. Chúc các bạn săn sale thành công và đừng quên chia sẻ cho bạn bè nhé!', 'https://images.unsplash.com/photo-1524289286702-f07229da36f5?q=80&w=2070&auto=format&fit=crop', 3, 17, NOW());
